lib/taskapp_web/router.ex
defmodule TaskappWeb.Router do
  use TaskappWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session #parses cookie header
    plug :get_current_user
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    # we dont fetch sessions here or get current user
    # how to authenticate?
    plug :accepts, ["json"]
  end

  def get_current_user(conn, _params) do
    user_id = get_session(conn, :user_id)
    user = Taskapp.Accounts.get_user(user_id || -1)
    assign(conn, :current_user, user)
  end

  scope "/", TaskappWeb do
    pipe_through :browser 
    get "/", PageController, :index

    resources "/managers", ManageController


    resources "/users", UserController
    resources "/tasks", TaskController

    post "/session", SessionController, :create
    delete "/session", SessionController, :delete

    get "/feed", PageController, :feed


  end

  scope "/api/v1", TaskappWeb do
    pipe_through :api
    resources "/times", TimeBlocksController, except: [:new, :edit]
  end 
end

lib/taskapp_web/templates/page/feed.html.eex
<%= if @current_user do %>
  <div class="row">
    <div class="col">
      <h1> Create New Task</h1>
      <%= render TaskappWeb.TaskView, "form.html",
          Map.put(assigns, :action, task_path(@conn, :create)) %>
    </div>
  </div>
<% end %>

<h1>Your Tasks</h1>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Time taken In Mins</th>
      <th>Task completed</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
<%= Enum.map @tasks, fn task -> %>
 

  <tr>
        <td><%= task.title %></td>
        <td><%= task.description %></td>
        <td><%= task.time_taken %></td>
        <td><%= task.task_completed %></td>
        <td class="text-right">
        <span><%= link "Show", to: task_path(@conn, :show, task), class: "btn btn-default btn-xs" %></span>
        </td>
  </tr>
    
    
    
 
<% end %>
  </tbody>
</table>

<h1>Tasks assigned by You to underlings</h1>
<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th> Assigned to </th>
      <th>Description</th>
      <th>Time taken In Mins</th>
      <th>Task completed</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
<%= Enum.map @underlings, fn underling -> %>
  <%= for task <- Taskapp.Tracker.get_tasks_of_underlings(underling.manages.id) do %>
  <tr>
        <td><%= task.title %></td>
        <td><%= underling.manages.name %> </td>
        <td><%= task.description %></td>
        <td><%= task.time_taken %></td>
        <td><%= task.task_completed %></td>
        <td class="text-right">
        <span><%= link "Show", to: task_path(@conn, :show, task), class: "btn btn-default btn-xs" %></span>
        <span><%= link "Edit", to: task_path(@conn, :edit, task), class: "btn btn-default btn-xs" %></span>
        <span><%= link "Delete", to: task_path(@conn, :delete, task), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %></span>
        </td>
  </tr>
  <% end %>
<% end %>
  </tbody>
</table>

lib/taskapp_web/templates/page/index.html.eex
<!-- <div class="jumbotron">
  <h2><%= gettext "Welcome to %{name}!", name: "Phoenix" %></h2>
  <p class="lead">A productive web framework that<br />does not compromise speed and maintainability.</p>
</div>

<div class="row marketing">
  <div class="col-lg-6">
    <h4>Resources</h4>
    <ul>
      <li>
        <a href="http://phoenixframework.org/docs/overview">Guides</a>
      </li>
      <li>
        <a href="https://hexdocs.pm/phoenix">Docs</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix">Source</a>
      </li>
    </ul>
  </div>

  <div class="col-lg-6">
    <h4>Help</h4>
    <ul>
      <li>
        <a href="http://groups.google.com/group/phoenix-talk">Mailing list</a>
      </li>
      <li>
        <a href="http://webchat.freenode.net/?channels=elixir-lang">#elixir-lang on freenode IRC</a>
      </li>
      <li>
        <a href="https://twitter.com/elixirphoenix">@elixirphoenix</a>
      </li>
    </ul>
  </div>
</div> -->
<center>
  <h1> Welcome to Task Managing Application </h1>
</center>
<div class="row">
  <div class="col">
    <h1>Log In</h1>
       <!-- session_path(@conn, :create) -->
      <%= form_tag("/session", method: :post) do %>
        <div class="form-group">
          name
          <input type="text" name="name" placeholder="user name" >
        </div>
        <!-- passwords come later -->
        <div class="form-group">
          <button class="btn btn-primary">Log in</button>
          <%= link "Register", to: user_path(@conn, :new),class: "btn btn-danger" %>
        </div>
      <% end %>
 </div>
</div>